/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommunityIcon: typeof import('./src/components/icons/CommunityIcon.vue')['default']
    DocumentationIcon: typeof import('./src/components/icons/DocumentationIcon.vue')['default']
    EcosystemIcon: typeof import('./src/components/icons/EcosystemIcon.vue')['default']
    FrameworkLink: typeof import('./src/components/FrameworkLink.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Island: typeof import('./node_modules/iles/dist/client/app/components/Island.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupportIcon: typeof import('./src/components/icons/SupportIcon.vue')['default']
    ToolingIcon: typeof import('./src/components/icons/ToolingIcon.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
